language: python

env:
  - TOXENV=django20
  - TOXENV=django21
  - TOXENV=django22


cache:
  - pip

install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt

script:
  - tox
