language: python

python:
  - 2.7
  - 3.6
  - 3.7

env:
  - TOXENV=django20
  - TOXENV=django21
  - TOXENV=django22

matrix:
  include:
    - python: 2.7
      env: TOXENV=quality
  allow_failures:
    - python: 3.6
    - python: 3.7
    - python: 2.7
      env: TOXENV=django20
    - python: 2.7
      env: TOXENV=django21
    - python: 2.7
      env: TOXENV=django22


cache:
  - pip

install:
  - pip install tox
  - pip install -r requirements.txt

script:
  - tox
